# Generated by Django 3.1.3 on 2020-12-09 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20201209_0728'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogdetailpage',
            old_name='custom_title',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='bloglistingpage',
            old_name='custom_title',
            new_name='description',
        ),
    ]
