# Generated by Django 3.1.3 on 2020-11-24 13:12

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_aboutpage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='body',
            new_name='intro',
        ),
        migrations.AddField(
            model_name='homepage',
            name='productIntro',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
    ]
