# Generated by Django 3.1.3 on 2020-11-24 13:23

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20201124_0713'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='about_the_teas',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='health_benefits',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='popular_teas',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
    ]
