# Generated by Django 3.1.3 on 2020-12-11 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_delete_blogpage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homepage',
            options={'verbose_name': 'Home Page', 'verbose_name_plural': 'Home Pages'},
        ),
    ]
