# Generated by Django 3.1.3 on 2021-01-02 00:09

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_formfield2_subscribeform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formfield2',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_fields2', to='home.subscribeform'),
        ),
    ]
