# Generated by Django 3.1.3 on 2021-01-06 01:02

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_auto_20210101_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpage',
            name='faq',
            field=wagtail.core.fields.StreamField([('ingredients_list', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('ingredient', wagtail.core.blocks.CharBlock()), ('amount', wagtail.core.blocks.CharBlock(required=False))]), form_classname='ingredients-list'))], blank=True, null=True),
        ),
    ]
