# Generated by Django 3.1.3 on 2021-01-06 01:45

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_auto_20210105_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutpage',
            name='faq',
            field=wagtail.core.fields.StreamField([('question', wagtail.core.blocks.CharBlock()), ('answer', wagtail.core.blocks.CharBlock(required=False))], blank=True, null=True),
        ),
    ]
