# Generated by Django 3.1.3 on 2021-01-06 01:59

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_auto_20210105_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutpage',
            name='faq',
            field=wagtail.core.fields.StreamField([('faq', wagtail.core.blocks.ListBlock(wagtail.core.blocks.CharBlock()))], blank=True, null=True),
        ),
    ]
