# Generated by Django 3.1.3 on 2021-01-06 02:02

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_auto_20210105_1959'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutpage',
            name='faq',
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='questions',
            field=wagtail.core.fields.StreamField([('questions', wagtail.core.blocks.ListBlock(wagtail.core.blocks.CharBlock()))], blank=True, null=True),
        ),
    ]
