# Generated by Django 3.1.3 on 2021-01-10 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_auto_20210105_2002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutpage',
            name='questions',
        ),
    ]
