# Generated by Django 3.1.3 on 2020-12-28 17:34

from django.db import migrations
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_productcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdetailpage',
            name='product_categories',
            field=modelcluster.fields.ParentalManyToManyField(blank='True', to='products.ProductCategory'),
        ),
    ]
