# Generated by Django 3.1.3 on 2020-12-28 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_productdetailpage_product_categories'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productdetailpage',
            old_name='product_categories',
            new_name='categories',
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='slug',
            field=models.SlugField(allow_unicode=True, help_text='Pick a Category', max_length=255, verbose_name='slug'),
        ),
    ]
