# Generated by Django 3.1.3 on 2020-12-28 21:37

from django.db import migrations, models
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20201228_1141'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductMood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(allow_unicode=True, help_text='Pick a Mood', max_length=255, verbose_name='slug')),
            ],
            options={
                'verbose_name': 'Product Mood',
                'verbose_name_plural': 'Product Moods',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='productdetailpage',
            name='moods',
            field=modelcluster.fields.ParentalManyToManyField(blank='True', to='products.ProductMood'),
        ),
    ]
