# Generated by Django 3.1.3 on 2020-12-29 21:10

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20201228_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdetailpage',
            name='price',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
    ]
